[[redirects]]
  # Proxy requests starting with /api/auth/ to the corresponding endpoint on your backend server
  from = "/api/auth/*"
  to = "https://podcast-stream.onrender.com/api/auth/:splat"
  status = 200
